# frozen_string_literal: true

require "json"
require "tmpdir"

RSpec.describe AffectedTests::MapMerger do
  describe ".run" do
    def run(map_infos)
      Dir.mktmpdir do |dir|
        map_file_paths = map_infos.each_with_index.map do |map_info, index|
          File.join(dir, "map-#{index}.json").tap { |path| File.write(path, JSON.dump(map_info)) }
        end
        output_path = File.join(dir, "merged.json")

        described_class.run(map_file_paths:, output_path:)

        JSON.parse(File.read(output_path))
      end
    end

    it "merges tests of each source file without duplication" do
      result = run([
        { revision: "rev", map: { "lib/foo.rb" => ["spec/foo_spec.rb"], "lib/bar.rb" => ["spec/bar_spec.rb"] } },
        { revision: "rev", map: { "lib/foo.rb" => ["spec/foo_spec.rb", "spec/integration_spec.rb"] } }
      ])

      expect(result).to eq(
        "revision" => "rev",
        "map" => {
          "lib/foo.rb" => ["spec/foo_spec.rb", "spec/integration_spec.rb"],
          "lib/bar.rb" => ["spec/bar_spec.rb"]
        }
      )
    end

    it "keeps a single map as it is" do
      result = run([{ revision: "rev", map: { "lib/foo.rb" => ["spec/foo_spec.rb"] } }])

      expect(result).to eq("revision" => "rev", "map" => { "lib/foo.rb" => ["spec/foo_spec.rb"] })
    end

    it "raises when the maps were generated by different revisions" do
      map_infos = [
        { revision: "rev-1", map: {} },
        { revision: "rev-2", map: {} }
      ]

      expect { run(map_infos) }.to raise_error("map files weren't generated by same revision")
    end

    it "raises when no map is given" do
      expect { run([]) }.to raise_error("map files weren't generated by same revision")
    end
  end
end
